const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.yagames_sdk,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Behaviors.TileMovement,
		C3.Behaviors.Tween,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Plugins.Arr,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Behaviors.MoveTo,
		C3.Plugins.Json,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.TileMovement.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Audio.Acts.Stop,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.TileMovement.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.TileMovement.Cnds.CanMoveTo,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurY,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.yagames_sdk.Acts.SetLeaderboardScore,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SubInstanceVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Browser.Acts.LoadStyleSheet,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsPreview
	];
};
self.C3_JsPropNameTable = [
	{YandexGamesSDK: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Audio: 0},
	{PlatformInfo: 0},
	{Browser: 0},
	{loading: 0},
	{pick: 0},
	{touch: 0},
	{cx: 0},
	{cy: 0},
	{crystal: 0},
	{switch: 0},
	{TileMovement: 0},
	{Tween: 0},
	{Solid: 0},
	{Flash: 0},
	{square: 0},
	{spawn: 0},
	{cell: 0},
	{pickcount: 0},
	{Array: 0},
	{scoret: 0},
	{bestscoret: 0},
	{crystalt: 0},
	{remove: 0},
	{Text: 0},
	{swapframe: 0},
	{swapframe2: 0},
	{fuid: 0},
	{suid: 0},
	{swap: 0},
	{b0: 0},
	{b1: 0},
	{b2: 0},
	{b3: 0},
	{b4: 0},
	{b5: 0},
	{b6: 0},
	{b7: 0},
	{b8: 0},
	{b9: 0},
	{b10: 0},
	{TiledBackground: 0},
	{countz: 0},
	{Sprite: 0},
	{ДвижениеК: 0},
	{Частицы: 0},
	{crown: 0},
	{gameover: 0},
	{win: 0},
	{bonus: 0},
	{JSON: 0},
	{close_btn: 0},
	{Частицы2: 0},
	{bonus_1024: 0},
	{close_btn2: 0},
	{close_btn3: 0},
	{timer: 0},
	{Синусоида: 0},
	{music: 0},
	{score: 0},
	{won_2048: 0},
	{best: 0},
	{touching: 0},
	{cvalue: 0},
	{gox: 0},
	{goy: 0},
	{rand: 0},
	{loose: 0}
];

self.InstanceType = {
	YandexGamesSDK: class extends C3.Plugins.yagames_sdk.Instance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	loading: class extends self.ISpriteInstance {},
	square: class extends self.ISpriteInstance {},
	cell: class extends self.ISpriteInstance {},
	Array: class extends self.IArrayInstance {},
	scoret: class extends self.ITextInstance {},
	bestscoret: class extends self.ITextInstance {},
	crystal: class extends self.ISpriteInstance {},
	crystalt: class extends self.ITextInstance {},
	remove: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	swap: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Частицы: class extends self.IParticlesInstance {},
	crown: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	win: class extends self.ISpriteInstance {},
	bonus: class extends self.ITextInstance {},
	JSON: class extends self.IJSONInstance {},
	close_btn: class extends self.ISpriteInstance {},
	Частицы2: class extends self.IParticlesInstance {},
	bonus_1024: class extends self.ISpriteInstance {},
	close_btn2: class extends self.ISpriteInstance {},
	close_btn3: class extends self.ISpriteInstance {},
	timer: class extends self.ITextInstance {},
	music: class extends self.ISpriteInstance {}
}